# permissions for end users to view captains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: captain-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: project-v3
    app.kubernetes.io/part-of: project-v3
    app.kubernetes.io/managed-by: kustomize
  name: captain-viewer-role
rules:
- apiGroups:
  - crew.testproject.org
  resources:
  - captains
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crew.testproject.org
  resources:
  - captains/status
  verbs:
  - get
